fix the missing notes about telegram.ext.JobQueue
if not use `pip install python-telegram-bot[job-queue]` to install PTB, will get `AttributeError: 'NoneType' object has no attribute 'get_jobs_by_name'` error.